
version: "3.6"
services:
  service:
    build: "./kapsule"
    ports:
      - "8080"
  client:
    build: "./kapsule-ui"
    ports:
      - "3000"
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "service"
      - "client"