version: "3.6"
services:
      
  kapsule-api:
    image: kapsule-api:latest
    container_name: kapsule-api
    ports:
      - "8080"
  
  kapsule-redirect:
    image: kapsule-redirect:latest
    container_name: kapsule-redirect
    ports:
      - "8080"
  
  client:
    image: kapsule-ui:latest
    ports:
      - "3000"
  
  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090"
    restart: always
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3005:3000
    depends_on:
      - "prometheus"
    env_file:
      - ./.env
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
 
  
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - "kapsule-api"
      - "kapsule-redirect"
      - "client"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    command:
      - '-nginx.scrape-uri=http://nginx:80/stub_status' 
    container_name: nginx-exporter
    ports: 
      - "9113"
    depends_on:
      - "nginx"
  
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


volumes:
  grafana-storage: {}
  prometheus_data: {}