
version: "3.6"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3005:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-storage:/var/lib/grafana
  service:
    build: ./kapsule
    container_name: kapsule-service
    ports:
      - "8080:8080"
      - "8081:8081"
  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
  client:
    build: ./kapsule-ui
    container_name: kapsule-ui
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.15-alpine
    container_name: kapsule-nginx
    ports:
      - "80:80"
    depends_on:
      - "service"
      - "client"
volumes:
  grafana-storage: {}
  prometheus_data: {}