
version: "3.6"
services:

  kapsule-api:
    build:
      context: ./kapsule
      dockerfile: Dockerfile-api
    container_name: kapsule-api
    ports:
      - 8080:8080
  
  kapsule-redirect:
    build:
      context: ./kapsule
      dockerfile: Dockerfile-redirect
    container_name: kapsule-redirect
    ports:
      - 8081:8080
  
  client:
    build: ./kapsule-ui
    container_name: kapsule-ui
    ports:
      - 3000:3000
  
  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090"
    restart: always
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3005:3000
    depends_on:
      - "prometheus"
    env_file:
      - ./.env
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
  
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./test:/etc/nginx/conf.d
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - "kapsule-api"
      - "kapsule-redirect"
      - "client"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    command:
      - '-nginx.scrape-uri=http://nginx:80/stub_status' 
    container_name: nginx-exporter
    ports: 
      - 9113:9113
    depends_on:
      - "nginx"
       

volumes:
  grafana-storage: {}
  prometheus_data: {}