global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: kapsule-api 
    metrics_path: /metrics
    static_configs:
      - targets:
        - service:8080
  - job_name: kapsule-redirect
    metrics_path: /metrics
    static_configs:
      - targets:
        - service:8081